apiVersion: v1
kind: Namespace
metadata:
  name: kyverno
  labels:
    name: kyverno
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: kyverno
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: v1.11.4
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    automated:
      prune: true
      selfHeal: true